--- #YAML:1.0
name:                Net-ThreeScale-Client
version:             0.1.2
abstract:            Client for 3Scale.com web API payments system
license:             ~
author:              
    - Owen Cliffe <zoot@zoot.org.uk>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    HTTP::Request:                 0
    LWP:                           0
    YAML:                          0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
